image: Visual Studio 2017

branches:
  only:
    - master

skip_commits:
  files:
    - '**/*.md'

assembly_info:
  patch: true
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
 
build:
  project: SuperStructs.sln
  verbosity: detailed
  publish_nuget: true
 
before_build:
  - nuget restore
 
nuget:
  account_feed: true
  project_feed: true
 
deploy:
  provider: NuGet
  api_key:
    secure: q+Y+Db0N+Pd+gyX6hc5FRMjAtpp0gSZjv+tu/gFci0I=
  skip_symbols: false
  artifact: /.*\.nupkg/