image: Visual Studio 2017
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
before_build:
  - cmd: dotnet restore
artifacts:

  # pushing a single file
  - path: superstructs.zip

  # pushing all *.nupkg files in build directory recursively
  - path: '**\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: q+Y+Db0N+Pd+gyX6hc5FRMjAtpp0gSZjv+tu/gFci0I=
  skip_symbols: false
  artifact: /.*\.nupkg/
