image: Visual Studio 2017

branches:
  only:
    - master

configuration: Release
platform: Any CPU

skip_commits:
  files:
    - '**/*.md'

nuget:
  account_feed: true

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

build:
  publish_nuget: true

test: off

before_build:
  - cmd: dotnet restore

artifacts:
  - path: artifacts/*.*nupkg

deploy:
  provider: NuGet
  api_key:
    secure: q+Y+Db0N+Pd+gyX6hc5FRMjAtpp0gSZjv+tu/gFci0I=
  skip_symbols: false
  artifact: /.*\.nupkg/
